### ISSUE TITLE
USER STORY: New User registration

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/carehub#1]
As a **Site User**, I can **register a new account** so that **I can add, edit, delete and comment on my articles**

**Acceptance Criteria**
- Signup button is easy to see and is on the homepage
- Signup button navigates to a signup page
- Signup page is easy to complete, and data is validated
- When signup details are complete, a click submit will create a new account
- When the new account is created, I am notified that the account creation was successful

**Tasks**
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
- [ ] Add signup link to navbar and to the home page
- [ ] Customise allauth signup form HTML template
- [ ] Create message to notify user of successfully creating a new account
