### ISSUE TITLE
USER STORY: Browse page of articles with Pagination

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/carehub#6]
As a **Site User**, I can **view a paginated list of articles** so that **I can view and browse the articles**

**Acceptance Criteria**
- On the main articles page the user can see a list view of each summary article, showing the title, an image and some of the information. 
- The user can clearly see what each article is about
- When the user clicks on an article, they get a full view of the complete article

**Tasks**
- [ ]  Create an Article class in views.py to show a list view of the articles
 - [ ]  Create a browse HTML template
- [ ]   Create a layout that is both responsive and easy to view the basic information of each article
- [ ]   Link the Summary Article to the Full Article page
 - [ ]  Add pagination
