### ISSUE TITLE
USER STORY: View full article

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/carehub#7]
As a **Site User**, I can **click on an article summary** so that **I can view the full version of the article and view 'tick as helpful' and comments left by users**

**Acceptance Criteria**
- on clicking a Summary Article the user is brought to the Full Article view
- the Article information is clearly displayed
- the user can view 'tick as helpful' and comments left by users

**Task**
- [ ] Link summary article to full article view
- [ ] Make full article easy to read and responsive
- [ ] Show 'tick as helpful' and comments left by users on page
